### ISSUE TITLE
Tag looks weird in replies

### ISSUE THREAD

**Issue by asportnoy** [Puyodead1/replugged-stafftags#5]
<img width="185" alt="Screenshot on 2022-12-21 at 10 45 59" src="https://user-images.githubusercontent.com/14863373/208959066-e0fe43fd-bc84-494a-abfb-3d10f2d694d1.png">
Should have a bit of padding between the tag and the username.

**Comment by OIRNOIR** [comment]
I just installed this plugin and it's still there. Is there a fix coming soon?
